version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: liga_rodzynkow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TwojeHasloZDockera # Musi być takie samo jak w appsettings.json!
      POSTGRES_DB: LigaRodzynkowDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: